# payment/.github/workflows/build.yml
name: Build Payment Service

on:
  push:
    branches: [main]
  workflow_dispatch: # Cho phép trigger thủ công

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR file
        uses: actions/upload-artifact@v4 # Cập nhật lên v4
        with:
          name: payment-jar
          path: target/*.jar
          retention-days: 5 # Tùy chọn: giữ artifacts trong 5 ngày
